name: Deploy CMP Web to Vercel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - uses: gradle/actions/setup-gradle@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm i -g vercel

      # 프로젝트 링크/환경 끌어오기
      - run: vercel pull --yes --environment=production
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      # vercel.json의 buildCommand/outputDirectory로 로컬 빌드
      - run: vercel build
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      # 사전빌드물 배포
      - run: vercel deploy --prebuilt --prod --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
